# Generated by Django 4.2.4 on 2023-08-24 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RentalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('rent', models.FloatField()),
                ('numberOfTenants', models.IntegerField(blank=True, default=5)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('locate', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(default=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.CharField(max_length=13, null=True)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('matchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='userIDA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.userinfor'),
        ),
    ]
