# Generated by Django 4.2.4 on 2023-08-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='userIDB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_userIDB', to='matching.userinfor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='userIDA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_userIDA', to='matching.userinfor'),
        ),
    ]
