# Generated by Django 4.2.4 on 2023-08-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_match_useridb_alter_match_userida'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfor',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
