# Generated by Django 4.2.4 on 2023-08-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_remove_userinfor_locate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='locate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
