# Generated by Django 4.2.4 on 2023-08-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_remove_userinfor_locate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
